force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Screening in progress</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>No show</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/recordTypes/Chevron.recordType-meta.xml
<RecordType>
    <fullName>Chevron</fullName>
    <active>true</active>
    <label>Chevron</label>
</RecordType>

force-app/main/default/classes/ChevronUpdate.cls
// Performing the upsert operation on Chevron so that the click on Chevron automatically gets reflected in the DB and
// vice-versa

public class ChevronUpdate {
	@AuraEnabled	
    public static void updateStatus(String JobAppStatus , String recordId){
        Job_Application__c jobApplicationObj = [Select Id ,Status__c from Job_Application__c where Id=:recordId] ; 
        jobApplicationObj.Status__c = JobAppStatus ; 
        upsert jobApplicationObj ;
        
    }
}