force-app/main/default/objects/Candidate__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>This is a picklist used to select the respective skills the candidates posses</description>
    <label>Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Machine learning</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>FullStack Development</fullName>
            </value>
            <value>
                <fullName>Software Development</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/DayBeforeJoin__c.field-meta.xml
<CustomField>
    <fullName>DayBeforeJoin__c</fullName>
    <description>To get the number of Days before joining</description>
    <formula>Joining_Date__c  -  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DayBeforeJoin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Screening in progress</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>No show</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <description>For the Default Purposes</description>
    <label>New</label>
</RecordType>

force-app/main/default/classes/JobApplicationTest.cls
// Test classes for JobApplication, EmailToCandidates, PositionController, ChangeRecordTypes and has
// a code coverage of more than 75% in each case

@isTest
public class JobApplicationTest {
	
    @isTest 
    static void TestforJobApplication(){
        Candidate__c cand = new Candidate__c(First_Name__c = 'Manohar');
        cand.Skills__c = 'C++;Java';
        
        insert cand;
        
        Position__c pos = new Position__c(Name='Testing');
        insert pos;
        
        System.debug('Candidate ID '+cand.Id);
        System.debug('Position ID '+pos.Id);
        Job_Application__c jobApp = new Job_Application__c(Candidate__c = cand.Id,Position__c = pos.Id,Status__c = 
                                                          'New');
        
        insert jobApp;		
        
    }
    
    @isTest
    static void TestforPositionController(){
        Position__c pos = new Position__c(Name='TestingController');
        insert pos;
        
        ApexPages.StandardController sc = new ApexPages.standardController(pos);
        
        PositionController controller = new PositionController(sc);
        
        controller.searchForCandidate();
    }
    
    @isTest(seeAllData = True)
    static void TestforChangeRecordTypes(){
        Job_Application__c jobObj = [Select Id,Candidate__c,Position__c,Status__c from Job_Application__c where Id = 'a025g000002apqTAAQ'];
        
        System.debug('Job Application '+jobObj);
        String statusVal = 'No show';
        jobObj.Status__c = statusVal;
        
        update jobObj;
        
        Job_Application__c jobObj1 = [Select Id,Candidate__c,Position__c,Status__c from Job_Application__c where Id = 'a025g000002apqTAAQ'];
        System.assertEquals('No show', jobObj1.Status__c, 'Error with Updating Values');
    }
    
    @isTest(seeAllData = True)
    static void TestEmailToCandidates(){
        Candidate__c cand = new Candidate__c(First_Name__c = 'BatchTesting',Email__c = 'akshaysu@qti.qualcomm.com');
        cand.Skills__c = 'C++;Java';
        
        insert cand;
        
        Position__c pos = new Position__c(Name='BatchTesting');
        insert pos;
        

        Job_Application__c jobApp = new Job_Application__c(Candidate__c = cand.Id,Position__c = pos.Id,Status__c = 
                                                          'New',Joining_Date__c = Date.newInstance(2021, 4, 26));
        
        insert jobApp;		
        
        Test.StartTest();
        
        Id batchprocessid = Database.executeBatch(new EmailToCandidates());
        
        Test.StopTest();
        
        List<Job_Application__c> jobTestList = [Select Candidate__r.Id,Candidate__r.First_Name__c,Candidate__r.Email__c from Job_Application__c where DayBeforeJoin__c < 2];
        for(Job_Application__c jobVal : jobTestList){
            System.assertNotEquals(null, jobVal.Candidate__r.Email__c, 'Email should not be Null');
        }
    }
    
}